feat: added Braze plugin
iterativelyhq/itly-sdk-python pull request #7
Opened 2021-03-21 11:07 UTC by falconandy

2021-03-23 21:44 UTC, justin-iteratively requested changes

2021-03-23 21:44 UTC, justin-iteratively commented on packages/plugin-braze/tests/test_braze.py
> +        assert requests == [
Thank you @falconandy for adding tests. To make this more manageable could you please break this down into multiple independent cases. Ideally each test would [follow AAA and the naming conventions outlined here](https://bitbucket.org/seasyd/analytics_backend/src/master/test/). E.g.

```
def test_braze(httpserver: HTTPServer):
    time_short = 0.1
    time_max = 999
    event_1 = Event('event-1', Properties(item1='value1', item2=1))
    event_2 = Event('event-2', Properties(item1='value2', item2=2))

    def before_each:
       httpserver.expect_request(re.compile('/users/track')).respond_with_data()
       base_url=httpserver.url_for('')
       
    def Id_BrazePlugin_IsBraze(httpserver: HTTPServer):
        p = BrazePlugin('My-Key', BrazeOptions(base_url=base_url)
        assert p.id() == 'braze'
        
    def Track_Immediate_MakesRequest(httpserver: HTTPServer):
        p = BrazePlugin('My-Key', BrazeOptions(
            base_url=base_url,
            flush_queue_size=1,
            flush_interval=timedelta(seconds=time_short),
        ))
        p.load()
        p.track("user-1", event_1)
        time.sleep(time_short * 2)

        assert p.id() == 'braze'
        
    def Flush_QueueSizeReached_MakesRequest:
        p = BrazePlugin('My-Key', BrazeOptions(
            base_url=base_url,
            flush_queue_size=3,
            flush_interval=timedelta(seconds=time_max),
        ))
        p.load()
        p.identify("user-1", Properties(item1='value1', item2=2))
        time.sleep(time_short)
        p.track("user-2", event_1)
        time.sleep(time_short)
        p.track("user-2", event_2)
        time.sleep(time_short)
        requests = _get_cleaned_requests(httpserver)
        assert requests == [{...}];

    def Flush_FlushIntervalReached_MakesRequest:
       ...

    def Shutdown_WithPendingEvents_FlushesAndMakesRequests:
       ....
```

2021-03-23 21:44 UTC, justin-iteratively commented on packages/plugin-braze/itly_plugin_braze/_braze_client.py
> +        data = self._to_braze_properties(properties)
I think Event properties need to use the key "properties" - https://www.braze.com/docs/api/objects_filters/event_object/#event-property-persistence

2021-03-23 21:44 UTC, justin-iteratively commented on packages/plugin-braze/itly_plugin_braze/_braze_plugin.py
> +    flush_queue_size: int = 75
I see in the docs 75 is the maximum number of events per request. I think we should enforce the max in our implementation and set the default queue size to something lower than max. https://www.braze.com/docs/api/basics/#api-limits

2021-03-23 21:44 UTC, justin-iteratively commented on packages/plugin-braze/itly_plugin_braze/_braze_plugin.py
> +        self._client.identify(
Can you please add some logging for the Plugin methods

2021-03-25 17:34 UTC, falconandy commented on packages/plugin-braze/tests/test_braze.py
> +        assert requests == [
Added more tests. Not sure about naming.

2021-03-25 17:35 UTC, falconandy commented on packages/plugin-braze/itly_plugin_braze/_braze_client.py
> +        data = self._to_braze_properties(properties)
I've copied the implementation from JS version. Fixed.

2021-03-25 17:35 UTC, falconandy commented on packages/plugin-braze/itly_plugin_braze/_braze_plugin.py
> +    flush_queue_size: int = 75
25?

2021-03-25 17:35 UTC, falconandy commented on packages/plugin-braze/itly_plugin_braze/_braze_plugin.py
> +        self._client.identify(
Added

2021-04-05 18:18 UTC, justin-iteratively commented on packages/plugin-braze/tests/test_braze.py
> +        assert requests == [
Tests look great. Thanks.

2021-04-05 18:19 UTC, justin-iteratively approved these changes

2021-04-05 18:19 UTC, merged